-- AlterTable
ALTER TABLE `user` MODIFY `firstName` VARCHAR(191) NULL,
    MODIFY `lastName` VARCHAR(191) NULL,
    MODIFY `phoneNumber` VARCHAR(191) NULL,
    MODIFY `userType` ENUM('AGRIPRENEUR', 'CLIENT', 'ADMIN', 'DELIVERY') NULL;
