import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter, Babylonica, Montserrat } from 'next/font/google';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { PanierProvider } from "./context/PanierContext";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({ subsets: ['latin'] })
const babylonica = Babylonica({ 
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-babylonica',
})
const montserrat = Montserrat({ 
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <PanierProvider>
      <html lang="en" className={`${inter.className} ${babylonica.variable} ${montserrat.variable}`}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        </body>
      </html>
      </PanierProvider>
    </ClerkProvider>
  )
}
